#!/bin/bash

source /lib/gentoo/functions.sh
#PORTAGE_BIN_PATH=$(python -c "import portage; print(portage.PORTAGE_BIN_PATH)")
#source ${PORTAGE_BIN_PATH}/isolated-functions.sh

die () {
    eerror $1
    exit $rc
}

ebegin "Sourcing custom scripts in .bashrc"
GIT_DIR=$(git rev-parse --show-toplevel)
SOURCE_LINE="source \"$GIT_DIR/env-init\""
grep -q -F "$SOURCE_LINE" $HOME/.bashrc || printf "\n# execute custom init script\n$SOURCE_LINE" >> $HOME/.bashrc
eend $?
rc=$?; if [[ $rc != 0 ]]; then die "Sourcing scripts failed"; fi

ebegin "Sourcing aliases"
# source aliases
for f in "$GIT_DIR"/aliases/*; do
	SOURCE_LINE="source \"$f\""
	grep -q -F "$SOURCE_LINE" $HOME/.bashrc || printf "\n$SOURCE_LINE" >> $HOME/.bashrc
done
eend $?
rc=$?; if [[ $rc != 0 ]]; then die "Sourcing aliases failed"; fi

# install /etc/portage/bashrc
ebegin "Installing /etc/portage/bashrc"
sudo cp -ax "$GIT_DIR"/portage-bashrc /etc/portage/bashrc
eend $?
rc=$?; if [[ $rc != 0 ]]; then die "Installing custom bashrc failed"; fi

# copy mounter
#ebegin "Installing shared dir mounter"
#NM_CONF_DIR="/etc/NetworkManager/dispatcher.d/"
#POST_CONN_HOOK="$NM_CONF_DIR/99-mounter"
#sudo cp -ax $GIT_DIR/network/mounter $POST_CONN_HOOK
# change owner to root
#sudo chown root:root $POST_CONN_HOOK
#eend $?
#rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi

ebegin "Running tests"
bats tests/ 2>1 1>/dev/null
eend $?
rc=$?; if [[ $rc != 0 ]]; then die "Tests failed - rerun \"bats tests/\" for details"; fi
