#!/bin/bash
GIT_DIR=$(git rev-parse --show-toplevel)
SOURCE_LINE="source \"$GIT_DIR/env-init\""
grep -q -F "$SOURCE_LINE" $HOME/.bashrc || printf "\n# execute custom init script\n$SOURCE_LINE" >> $HOME/.bashrc
