#!/bin/bash

function _run {
	ARCH=$(uname -m)
	qemu-system-$ARCH \
			-enable-kvm \
			-bios $HOME/bin/efi-bios.bin \
			-cpu host \
			-smp 2 \
			-m 4G \
			-drive file="$1",if=virtio \
			-netdev user,id=vmnic,hostname="vm-$(basename $1)" \
			-device virtio-net,netdev=vmnic \
			-monitor stdio \
			-display sdl \
			-vga cirrus \
			-name "vm-$(basename $1)" $@
}

alias qemu-run='_run'
