#!/bin/bash
#			-drive file="$1",if=virtio \


function _run {
	EFIBIOS="$HOME/bin/efi-bios.bin"
	if [ ! -f "$EFIBIOS" ]; then
		echo -e "efi bios file not found!" && exit 1
	fi
	ARCH=$(uname -m)
	qemu-system-$ARCH \
			-enable-kvm \
			-cpu host \
			-smp 2 \
			-m 4G \
			-hda "$1" \
			-netdev user,id=vmnic,hostname="vm-$(basename $1)" \
			-device virtio-net,netdev=vmnic \
			-monitor stdio \
			-display sdl \
			-vga cirrus \
			-name "vm-$(basename $1)" \
			"${@:2}" \
			-bios "$EFIBIOS"
}

alias qemu-run='_run'
