#!/bin/sh

if [[ "$1" != *.img ]]; then
	echo No img passed.
	exit 1
fi

FILENAME=$(basename $1)
NAME=$(echo $FILENAME | rev | cut -c 5- | rev)
echo $NAME

exec qemu-system-x86_64 -enable-kvm \
	-cpu host \
	-drive file=$1,if=virtio \
	-net nic,macaddr=$(qemu-mac-hasher "$1") -net user,hostname="$NAME" \
	-m 2048M \
	-bios efi-bios.bin \
	-monitor stdio \
	-display sdl \
	-vga cirrus \
	-snapshot \
	-name "$NAME" \
	$@

