#!/bin/sh

#-netdev user,id=vmnic,hostname=gentoovm -device virtio-net,netdev=vmnic \

if [[ "$1" != *.img && "$1" != *.qcow2 ]]; then
	echo No img passed.
	exit 1
fi

FILENAME=$(basename $1)
NAME=$(echo $FILENAME | rev | cut -c 5- | rev)
echo $NAME

exec qemu-system-x86_64 -enable-kvm \
	-bios $(dirname $0)/efi-bios.bin \
	-boot order=c \
	-cpu host \
	-smp 2 \
	-m 4G \
	-drive file=$1,if=virtio \
#	-net nic,macaddr=$(qemu-mac-hasher "$1") -net user,hostname="$NAME" \
	-netdev user,id=vmnic,hostname="$1"vm -device virtio-net,netdev=vmnic \
	-monitor stdio \
	-display sdl \
	-vga cirrus \
	-snapshot \
	-name "$NAME" \
	$@

